### ISSUE TITLE
can support subversion 1.12 ?

### ISSUE THREAD

**Issue by MarkYeh75** [subclipse/subclipse#100]
as ttile : 

can support subversion 1.12 with javahl 1.12

**Comment by markphip** [comment]
I have added an update site with the SVN 1.12 JavaHL bits here:

 https://dl.bintray.com/subclipse/releases/javahl/snapshot-1.12/

Just add this as an update site and you can install the JavaHL 1.12 to an existing installation.  Once I get some success feedback I will update the main Subclipse update site to pull in this version in addition to the others.

**Comment by markphip** [comment]
Keep in mind there are no changes to Subclipse itself.  This just brings in the newer SVN API so that you can use the native 1.12 libraries.

**Comment by PyvesB** [comment]
Have updated and performed a few SVN operations, all seems good so far. 👍

**Comment by ceuer** [comment]
hello,myeclipse install from stie error:

~~~
Cannot complete the install because one or more required items could not be found.
  Software being installed: Subversion 1.12 JavaHL 1.12.0.201906051957 (org.tigris.subversion.clientadapter.javahl.feature.feature.group 1.12.0.201906051957)
  Missing requirement: Subversion 1.12 JavaHL 1.12.0.201906051957 (org.tigris.subversion.clientadapter.javahl.feature.feature.group 1.12.0.201906051957) requires 'org.eclipse.equinox.p2.iu; org.tigris.subversion.clientadapter 0.0.0' but it could not be found
~~~

**Comment by markphip** [comment]
Have you installed Subclipse?  The update site in this ticket is just for the SVN API that Subclipse uses. The error implies you do not have the current version of Subclipse installed.  Install that first, and then install the SVN 1.12 API.

**Comment by ceuer** [comment]
As you said, it's solved.Thank you.👍

**Comment by halbtuerke** [comment]
The changes also work for me.

Thanks for the fix.

**Comment by vickllny** [comment]
👍

**Comment by johannes-lode** [comment]
works for me on recent Gentoo with recent Eclipse 2020-03 and subversion-1.12
