### ISSUE TITLE
Incompatible JavaHL library loaded.  Subversion 1.10.x required

### ISSUE THREAD

**Issue by OldYoung** [subclipse/subclipse#109]
mac brew install subversion 1.12.2 , eclipse-2019-06,  subclipse is installed from https://dl.bintray.com/subclipse/releases/subclipse/latest/
and also i install javahl1.12 from https://dl.bintray.com/subclipse/releases/javahl/snapshot-1.12/
not works, I don't how to solve it, help!

**Comment by markphip** [comment]
If that is the error message you are getting, then you do not have the JavaHL 1.12 plugin installed.  You have the right update site for it, but it must not be installed.

**Comment by OldYoung** [comment]
I have seen javahl in installed software
about eclipse--> Installation Details-->Subversion 1.12 JavaHL
but still have the error message Incompatible JavaHL library loaded. Subversion 1.10.x required

**Comment by markphip** [comment]
Somehow it seems like the 1.10.x plugin has to still be running because the error message comes from the plugin and contains the expected version number as a static string in the error message.  So your error referencing 1.10.x implies that is the version of the plugin that is loaded.

Maybe try removing some plugins and installing again?

**Comment by OldYoung** [comment]
solved , this is my mistake, I install eclipse at ~/eclipse and move it to /Applications folder, this step make it wrong load plugins. thanks for your help.
