### ISSUE TITLE
Various issues with MacOS (Eclipse, subversion 1.13.0, merges not working)

### ISSUE THREAD

**Issue by thinginabook** [subclipse/subclipse#113]
Hello,

In the past I had no similar issues with JavaHL, Subversion and Subclipse in Eclipse. My machine got wiped and I had to reinstall everything again, but now I can't get it to work.

I currently work with MacOS High Sierra 10.13.6.

First, Subclipse 4.3.0 works with Subversion 1.10 or 1.11, but Homebrew is currently installing 1.13 and there's no way to install other version (the other option is installing Subversion 1.8... and that's it). This way I cannot select JavaHL from the SVN menu in Eclipse's preferences. While I can actually do checkouts and operate with SVN normally (?), I get stumped when merging, even when I swap JavaHL for SVNKit. When installing Subclipse I get the whole package from the marketplace, including JavaHL and SVNKit. It just doesn't work.

Merging with the CollabNet Desktop (Under Diff/Merge > Merge implementation) gives me the following error: 

"svn: E200007: Runner for 'org.tmatesoft.svn.core.wc2.SvnMerge' command have not been found; probably not yet implement in this API."

Then I switched to Subclipse's default merging implementation, but I need to select all revisions and this doesn't work in this option.

I'm honestly pulling my hair here. What I'm doing wrong? How can I get this running before I scrap Subclipse and just go with SmartSVN instead?

Thanks in advance.

**Comment by saoj** [comment]
I suggest you install Subversion 1.11 from Homebrew. No need to go with the latest version in my opinion. Here is how to do that:
```
$ git clone https://github.com/Homebrew/homebrew-core.git
$ cd homebrew-core
$ git checkout 14b7a2d1267d8cad05726803cb5c6132b689d80c Formula/subversion.rb
$ brew install --build-from-source Formula/subversion.rb
```
Wait because this install will take a long time, specially when it reaches the _make_ command. It is normal. And you might have to run the _brew install_ twice (last line above). Do a `brew list` to see if subversion was installed. If not, run the install again.

Close and open terminal, do `svn --version` and you should see version 1.11. Then install subclipse 4.3.0. I'm using SVNKit because JavaHL asks for password forever. Not sure how to fix that and not sure what is the advantage of JavaHL if you are also using the  command-line SVN too through the terminal. You can install JavaHL and decide later which one you want to use. You can switch back and forth between then after you install subclipse.

To use JavaHL you need to do:
`sudo ln -s /usr/local/lib/libsvnjavahl-1.dylib /Library/Java/Extensions/libsvnjavahl-1.dylib`

Note: When installing subclipse use `https://dl.bintray.com/subclipse/releases/subclipse/latest/`. 4.3.0 did not show JavaHL option for me.

**Comment by netslow** [comment]
I got the error. Please help.
`scons: Reading SConscript files ...
  File "/private/tmp/subversion--serf-20200425-24493-14p0e2z/serf-1.3.9/SConstruct", line 186

    print 'Warning: Used unknown variables:', ', '.join(unknown.keys())

          ^

SyntaxError: invalid syntax`

**Comment by markphip** [comment]
Subclipse has been updated to support all SVN versions up to and including 1.14.
