### ISSUE TITLE
Subclipse cannot be installed on Eclipse CPP 2020-06

### ISSUE THREAD

**Issue by pimvullers** [subclipse/subclipse#141]
Hi,

I'm experiencing same issue as reported here: https://stackoverflow.com/questions/63767517/not-able-to-install-subclipse-4-3-0-plugin-in-eclipse-ide-2020-06

Cannot complete the install because some dependencies are not satisfiable
  Software being installed: a.jre.javase 10.0.0
  Software currently installed: C/C++ Autotools support 9.11.1.202004012023 (org.eclipse.cdt.autotools.feature.group 9.11.1.202004012023)
  Cannot satisfy dependency:
    From: C/C++ Autotools support 9.11.1.202004012023 (org.eclipse.cdt.autotools.feature.group 9.11.1.202004012023)
    To: org.eclipse.equinox.p2.iu; org.eclipse.tools.templates.freemarker.java11 [1.1.100.202001140305,1.1.100.202001140305]
  Cannot satisfy dependency:
    From: Template Engine Freemarker Support (Java 11) 1.1.100.202001140305 (org.eclipse.tools.templates.freemarker.java11 1.1.100.202001140305)
    To: osgi.ee; (&(osgi.ee=JavaSE)(version=11))

Installing subclipse in Eclipse Java 2020-06 works.

I've tried installing both from zip and marketplace, same result. Can the dependencies be relaxed to allow installation on Eclipse CPP 2020-06, or do you have another resolution?

**Comment by markphip** [comment]
This problem is not related to Subclipse. These are not dependencies or features being installed for Subclipse. I have seen problems like this before. I believe your current plugin configuration is invalid .. for the reasons specified in the error message .. and it is basically going to prevent you from installing any other plugins until the problem is rectified. It looks like the problem is with the CDT plugins so maybe they can be reinstalled or updated and it will correct the problem. From what I can tell you have a plugin installed that requires Java 11 but you are running with Java 10?
