### ISSUE TITLE
Which class is the entry point when Eclipse commit and synchronize calls

### ISSUE THREAD

**Issue by zhanghb1994** [subclipse/subclipse#143]
Hi, I developed our project using Eclipse and managed the source code using SVN. Some personal profiles that should not have been submitted were submitted by others, but after setting the svn:ignore attribute, you will still see the files you want to ignore in the synchronization panel. So I wanna know that which class is the entry point when Eclipse commit and synchronize action calls, I wanted to see if I could change the plug-in code to ignore the file! Very very thanks.

**Comment by markphip** [comment]
The Synchronize process is pretty complex, I do not really understand it, it comes from Eclipse. I would probably start here:  https://github.com/subclipse/subclipse/tree/master/bundles/subclipse.core/src/org/tigris/subversion/subclipse/core/sync

Note you cannot ignore a file that has been added. The ignore feature only applies to unversioned files. So you would have to delete the files from the repository, get the working copy fully updated so that those files are now unversioned, and then you should be able to ignore them.

**Comment by zhanghb1994** [comment]
ok, let me see, thanks
