### ISSUE TITLE
Version Release Update Links Are Broken

### ISSUE THREAD

**Issue by zedseven** [subclipse/subclipse#192]
In the wiki and elsewhere, the specific version releases are linked to with https://subclipse.github.io/updates/subclipse/1.8.x (for example).

These links all lead to a 404. From what I can tell all links to specific versions are broken:
- https://subclipse.github.io/updates/subclipse/4.3.x
- https://subclipse.github.io/updates/subclipse/4.2.x
- https://subclipse.github.io/updates/subclipse/1.12.x
- https://subclipse.github.io/updates/subclipse/1.10.x
- https://subclipse.github.io/updates/subclipse/1.8.x

However the latest release seems to work:
https://subclipse.github.io/updates

This makes it much more difficult to get a specific version of the plugin for legacy SVN support.

**Comment by markphip** [comment]
The update sites are not designed for web browsers. You get a 404 because there is no index.html file at the location. These are all Eclipse update sites and the URL's are only designed to be entered into the Eclipse install/update UI. It knows that to do with the URL's ... which is to request the Eclipse-specific p2 files that drive the installer.
