### ISSUE TITLE
Customization svn info

### ISSUE THREAD

**Issue by zacisco** [subclipse/subclipse#199]
hello
how customize inline svn info?
for example: in "subversive" near modified file/folder shows > symbol
in "subclipse" shows small yellow * and can not see it
+ how change text color for info (svn version, date, user)

**Comment by markphip** [comment]
It has been years since I looked at Subversive, but the way we customize it is the same way they do (or did) which is the same way the Eclipse CVS plugin did it. There is a preference page under Team > SVN where you can customize the decorators:

<img width="823" alt="Screen Shot 2021-11-03 at 12 06 34 PM" src="https://user-images.githubusercontent.com/933108/140098069-a8cb8ddb-fee5-4239-80a5-69d511f67a1c.png">

**Comment by zacisco** [comment]
but can't change visualization for dirty files/folders.
I want add symb > as in subversive. it's real?

**Comment by markphip** [comment]
It is not going to do any good to phrase questions in relation to Subversive because I have obviously never used it and only looked at it a few times 10+ years ago. This project existed for years before Subversive was created so I do not know everything they did that was different.

If you want to display ">" for dirty files/folders then enter that in the field "Label decoration for outgoing" in the preferences. If you want to change the font or color those settings are on a different Eclipse page but it is linked to from our page.

**Comment by zacisco** [comment]
sorry for that ... mb i was blinded and don't saw settings for dirty elements.

**Comment by markphip** [comment]
In fairness, I do not think there is anything about this UX that is super obvious. I am guessing we copied the CVS plugin way back in the day.

**Comment by zacisco** [comment]
label is what i needed,thx and sorry again
