### ISSUE TITLE
Fix package export for the svnapi.javahl bundle

### ISSUE THREAD

**Issue by wtlnw** [subclipse/subclipse#60]
The current package export definition in [MANIFEST.MF](https://github.com/subclipse/subclipse/blob/master/bundles/svnapi.javahl/META-INF/MANIFEST.MF) is inconsistent:

```
Export-Package: org.apache.subversion.javahl,
 org.apache.subversion.javahl.callback,
 org.tigris.subversion.clientadapter.javahl,
 org.tigris.subversion.svnclientadapter.javahl
```

Types contained in the `org.apache.subversion.javahl.types` package are used in the exported `org.apache.subversion.javahl.callback` package (e.g. in `org.apache.subversion.javahl.callback.StatusCallback`) but cannot be actually used since the `types` subpackage is not exported.

In order to make the package export consistent again, the `types` subpackage should be exported as well.

**Comment by markphip** [comment]
I will look into this, but can you tell me is this specifically related to the SVN 1.10 changes I started working on yesterday?  I can see if new packages were added I would have not noticed.  Otherwise wondering are you trying to use this plugin yourself in some external code or something or are you seeing a bug when using Subclipse?

**Comment by wtlnw** [comment]
@markphip 
Thanks for the quick reply. This issue has bugged me for quite some time now (since subclipse 4.2.0), so it doesn't seem to be SVN 1.10.x specific.

I'm currently porting [subcherry](https://github.com/haumacher/subcherry) to be used inside eclipse as a plugin with its own user interface. Since subclipse is my SVN plugin of choice, the idea is to provide custom cherry picking functionality based on trac. The current subcherry implementation however provides its own JavaHL bindings. So, in order to get rid of these, I'd like to use the JavaHL bindings already packaged with subclipse.

The longterm goal is to migrate subcherry completely to use the `ISVNClientAdapter` interface but that's going to take quite a while. In the mean time I'd like to get it working with subclipse.

**Comment by markphip** [comment]
I made the changes, but it will be a while before it shows in a release build.  I switched master yesterday to working on SVN 1.10 support.  So the snapshot build that is available with this change will also mean you need SVN 1.10 JavaHL binaries.  I did also make the change on the 4.2.x branch but since I just pushed a release yesterday I am going to wait a while before I do another one.

**Comment by wtlnw** [comment]
Upgrade is not a problem here, so I can live with that. Thanks for the very fast response, markphip!
