### ISSUE TITLE
Support for SVN 1.11

### ISSUE THREAD

**Issue by mbooth101** [subclipse/subclipse#79]
Hi,

I received this bug in Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1653753

Fedora updated to SVN 1.11, but Subclipse does not yet appear to support it:

"Incompatible JavaHL library loaded.  Subversion 1.10.x required."

**Comment by markphip** [comment]
I do not know if I am going to support it unless help arrives to take over.

Subversion has moved to an LTS model with 1.10.x being the current LTS version. So if I did anything I planned to get on to 1.10 in a released version.

The problem is that Subclipse provides the Java part of JavaHL and due to how JNI works the Java part has to match the native part.  So we cannot just reliably relax the restriction and have things work.  There were not a lot of changes in 1.11 so maybe it is binary compatible for JNI purposes but that is not always the solution.

**Comment by markphip** [comment]
I did take a look and there is no way that 1.10.x and 1.11.x can share the same JavaHL code.  So there would have to be an explicit 1.11 version created in order to support this.  Since Fedora does its own build, it could patch the version check in the client adapter and then replace the javahl-1.10.0.jar with the 1.11 version.

**Comment by markphip** [comment]
The attached zip has a JAR for the JavaHL and Client Adapter.  If you drop these into the lib folder of the javahl client adapter plugin and either rename them to replace the two existing JAR's or update the MANIFEST.MF to change the file names to these, then it ought to work with the 1.11 native libraries.  I have not tried it though.

[javahl-1.11.zip](https://github.com/subclipse/subclipse/files/2654577/javahl-1.11.zip)

**Comment by markphip** [comment]
BTW, what I did was I updated the JavaHL and SVNClientAdapter builds to produce these JARs and publish them to [Maven](https://dl.bintray.com/subclipse/maven/) then just grabbed them from that repos.  That is how I would do it if I intended to release them in Subclipse, except I would commit the JARs to master in this repos and update the plugin manifest etc.

**Comment by edmh007** [comment]
Thanks! This worked right out of the box!

**Comment by markphip** [comment]
I have made some good progress on this.

On the snapshot update site I have made some changes. The JavaHL plugin has been moved out of the Subclipse feature into its own feature. This allows us to host multiple versions of it and I have a 1.10 and 1.11 version on the site. You can only have one installed so the highest version is going to win, keep that in mind. On Windows this is no big deal, you will just get 1.11 but on an OS where the JavaHL library comes from an external package make sure you install the version that matches your installed library. And if that version is 1.10 you might need to take care when you tell Eclipse to update all your installed plugins to not have it blindly just update you to the 1.11 version.

Other than that difference though it seems to work as intended which is good.  Hopefully people interested in this issue will install the latest snapshot to verify.  I will leave the issue open until this graduates to an official release ... which will be somewhat soon.

**Comment by markphip** [comment]
This is now available in the released 4.3.0 version
